### ISSUE TITLE
Need option to export the audio files

### ISSUE THREAD

**Issue by githubtrip** [jacbz/Lofi#1]
Great stuff.  Will be good for vlog background music. How to export the audio files?

**Comment by jacbz** [comment]
The audio is synthesized on the fly in the browser, and there is no native way to do this, neither through Tone.js nor the Web Audio API. I'm afraid you'll have to use external software like Audacity to manually record the audio as it is being played. Sorry.

**Comment by jlcarvalho** [comment]
Actually, you can use the Tone.js Recorder: https://tonejs.github.io/docs/14.7.39/Recorder
