### ISSUE TITLE
start training with per-trained

### ISSUE THREAD

**Issue by AmirMz1** [jacbz/Lofi#12]
Hi, can we run the model with a pre-trained model?
or resume training.

pls, can you show me how to use this, I didn't understand exactly, until now I only worked on computer vision, I need to learn about Transformers

**Comment by jacbz** [comment]
There is a pre-trained model you can download [here](https://github.com/jacbz/Lofi/files/7519187/checkpoints.zip). Or you can train your own model using the process described in the `model` folder.
