### ISSUE TITLE
Change average length of song

### ISSUE THREAD

**Issue by valientegaston** [jacbz/Lofi#15]
Impressive project! My congratulations! The generated music is very good. I have a question, is it possible that the average duration is 3 minutes instead of 1:30? I have downloaded the code but I can't figure out where to modify to achieve that. I clarify I do not program in python. Thank you!

**Comment by jacbz** [comment]
Increasing the duration will only increase the number of loops, not generate longer chord or melody sequences. You can change the number of loops here:

https://github.com/jacbz/Lofi/blob/a379facc79972ed573cb317640abbb0e600f5586/client/src/producer.ts#L175
