### ISSUE TITLE
Error when generating a new Play List

### ISSUE THREAD

**Issue by xuxun45** [jacbz/Lofi#4]
The error is in the web version https://lofi.jacobzhang.de.

The same error in my virtual machine with a fork made to try to improve and add a new collection of lead sheets and be able to improve the project.

![image](https://user-images.githubusercontent.com/68945526/184586894-5a335ddc-9d6e-466b-aa0b-aa7f589a46c0.png)

**Comment by jacbz** [comment]
@xuxun45 Thanks for the report, it seems the server is down. In the meantime, click [here](http://lofi.jacobzhang.de/?default) for a pre-generated playlist.

**Comment by xuxun45** [comment]
Thanks for your answer!.

I Download a local code fork on a VM. I changed the values calling to your server in /client/src/api.ts.
I got the same "Error!" on my local machine. I understand that there is some other part of the code that is calling to your server, which is down.
Could you help me to make it work locally?

**Comment by jacbz** [comment]
Hi, to use a local server, simply replace the line in https://github.com/jacbz/Lofi/blob/950a41c29c3faa61bf361ba71021188fb242d49a/client/src/api.ts#L9 with the URL to your server, e.g. localhost.

**Comment by xuxun45** [comment]
Hello!
I think that doesn't work for me.
I have downloaded the code again. I've got the flask server up. I've changed the values in the client/src/api.ts file again and brought up the development server using "npm run serve".

I get the same "Error!"
Thanks!


![1](https://user-images.githubusercontent.com/68945526/184958940-ab75473c-7fb3-42d7-ad7e-bd6accbf0015.png)

**Comment by jacbz** [comment]
You have to change the address to whatever IP your server is running on. In this case, it's port 5000, not 8080.

**Comment by xuxun45** [comment]
yeah! Its work!

Thank you very much @jacbz
