### ISSUE TITLE
"Error!"

### ISSUE THREAD

**Issue by Enjip** [jacbz/Lofi#5]
Since some days, I have an Error when I click on generate, Even when I use your website, Is it still an active project? Thanks :)

**Comment by Enjip** [comment]
![Uploading Capture.JPG…]()

**Comment by Enjip** [comment]
(if the upload doesn't work): [blob:https://imgur.com/de651820-f460-4ffe-9129-df47def4347a](url)

**Comment by jacbz** [comment]
@Enjip I'm afraid the server is currently down (see also #4). Until it is back up, I'm afraid you'll have to run the server locally. Sorry!

**Comment by Enjip** [comment]
Well, I know I'm doing something wrong but I don't find the solution to run it localy. Could you help me?  https://imgur.com/a/AghSZEL

**Comment by jacbz** [comment]
You need to run the Python server in the `server` folder first; there is a Dockerfile which you can use. After the server is running, you can change the address in the client to your server's.

**Comment by jacbz** [comment]
@Enjip The server is now running again.

**Comment by Enjip** [comment]
Okay, perfect thanks!
